{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(go_metrics_prometheus_Requests[1m]) * 60\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reservations Payment Success/Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "go_metrics_prometheus_ReservationPaymentSuccess",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_metrics_prometheus_ReservationPaymentFailure",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reservations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "go_metrics_prometheus_Reservations",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}